packages:
  - packages/*
  - playground/*
catalogs:
  build:
    '@originjs/vite-plugin-federation': ^1.4.1
    '@vitejs/plugin-vue': ^5.2.4
    '@vitejs/plugin-vue-jsx': ^4.1.2
    rollup-plugin-visualizer: ^5.14.0
    tsup: ^8.5.0
    unbuild: ^3.5.0
    unplugin-auto-import: ^19.2.0
    unplugin-vue-components: ^28.5.0
    unplugin-vue-router: ^0.12.0
    vite: ^6.3.5
    vite-plugin-dts: ^4.5.4
    vite-plugin-dynamic-base: ^1.1.0
    vite-plugin-jspm: ^0.6.1
    vite-plugin-vue-devtools: ^7.7.6
  dev:
    '@jspm/generator': ^2.6.0
    bumpp: ^10.1.1
    czg: ^1.11.1
    pncat: ^0.1.8
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    turbo: ^2.5.3
    typescript: ^5.8.3
  i18n:
    '@intlify/unplugin-vue-i18n': ^6.0.8
  lint:
    '@antfu/eslint-config': ^4.13.1
    eslint: ^9.27.0
    eslint-flat-config-utils: ^2.0.1
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.0.0
    prettier-plugin-tailwindcss: ^0.6.11
  prod:
    '@clack/prompts': ^0.10.1
    deepmerge: ^4.3.1
    find-up: ^7.0.0
    local-pkg: ^1.1.1
    pkg-types: ^2.1.0
  script:
    tsx: ^4.19.4
  test:
    vitest: ^3.1.3
  types:
    '@types/node': ^22.15.19
  utils:
    dayjs: ^1.11.13
